services:
  redis-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    restart: always

  backend:
    build: ./backend
    container_name: employee_manager_backend_container
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - SERVER_PORT=4000
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyOTYyMzc1NywiaWF0IjoxNzI5NjIzNzU3fQ.c6_mZDBpdVvDcxIQlC9RkJDV9NmVv8Y7pywkNVxsEkE
      - MONGO_BASE_URL=mongodb+srv://{{{username}}}:{{{password}}}@cluster0.xfvev.mongodb.net/{{{database_name}}}
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=h4fa6Jg9IPuqZMAj
      - MONGO_DATABASE_NAME=employee_manager_v1
      - REDIS_URL=redis://redis-service:6379
    depends_on:
      redis-service:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: employee_manager_frontend_container
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
